### PR TITLE
Added standard Travis config

### PR DESCRIPTION
**Pull request by helpfulrobot**
Hello!

I'm helpful robot. I noticed you have a tests folder but no Travis config file. I think this one might work for you.

Have a nice day! [grrrrbbrrrbb]

### CODE REVIEW

**Comment by tractorcow** [comment]
Restart travis.

**Comment by tractorcow** [comment]
Bug in your .travis.yml: Should be `securityextras/tests` not `silverstripe-securityextras/tests`

**Comment by tractorcow** [comment]
It doesn't need an installer name; The package name by itself is enough.

`	"name": "silverstripe/securityextras",`

**Comment by dhensby** [comment]
still not fixed @helpfulrobot

**Comment by assertchris** [comment]
Do your damn job, @helpfulrobot!

**Pull request closed without merging**
